#!/bin/sh
alias rc=riverctl

# General preferences
rc focus-follows-cursor normal

# Set background and border color
rc background-color 0x282a36
rc border-color-focused 0xbd93f9
rc border-color-unfocused 0xff79c6

# Set repeat rate
rc set-repeat 50 300

# App preferences

# Make certain views start floating
rc float-filter-add app-id float
rc float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
rc csd-filter-add app-id "gedit"

rc default-layout rivertile

# Subscripts
~/.config/river/keybindings
~/.config/river/startup
