syntax on

set tabstop=2
set shiftwidth=2
set expandtab

set number relativenumber
set splitbelow splitright
set hidden

hi StatusLine cterm=none ctermfg=15
hi StatusLineNC cterm=none ctermfg=7
hi VertSplit cterm=NONE ctermfg=3
hi SignColumn ctermbg=NONE

let mapleader=' '
nnoremap <leader><space> :GFiles<CR>
nnoremap <leader>, :Buffers<CR>
nnoremap <leader>bb :Buffers<CR>
nnoremap <leader>bk :bd<CR>
nnoremap <leader>ff :Files<CR>
nnoremap <leader>fs :w<CR>
nnoremap <leader>gf :GFiles?<CR>
nnoremap <leader>w <C-w>
