# Don't do anything smart for dumb terminals
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

ZSH="$HOME/.local/oh-my-zsh"
ZSH_CUSTOM="$HOME/.local/zsh-custom"

COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"

plugins=(
  docker
  docker-compose
  git
  github
  vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.anyshrc
