[".local/oh-my-bash"]
type = "git-repo"
url = "https://github.com/ohmybash/oh-my-bash.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/zsh-custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/zsh-custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/sheerun/start/vim-polyglot"]
type = "git-repo"
url = "https://github.com/sheerun/vim-polyglot.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/tpope/start/vim-repeat"]
type = "git-repo"
url = "https://github.com/tpope/vim-repeat.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/tpope/start/vim-sensible"]
type = "git-repo"
url = "https://github.com/tpope/vim-sensible.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/tpope/start/vim-surround"]
type = "git-repo"
url = "https://github.com/tpope/vim-surround.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/junegunn/start/fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/junegunn/start/fzf.vim"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.vim.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/jiangmiao/start/auto-pairs"]
type = "git-repo"
url = "https://github.com/jiangmiao/auto-pairs.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
type = "git-repo"
url = "https://github.com/wbthomason/packer.nvim.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"
