[".local/oh-my-bash"]
type = "git-repo"
url = "https://github.com/ohmybash/oh-my-bash.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/zsh-custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/zsh-custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/sheerun/start/vim-polyglot"]
type = "git-repo"
url = "https://github.com/sheerun/vim-polyglot.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/tpope/start/vim-repeat"]
type = "git-repo"
url = "https://github.com/tpope/vim-repeat.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/tpope/start/vim-sensible"]
type = "git-repo"
url = "https://github.com/tpope/vim-sensible.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/tpope/start/vim-surround"]
type = "git-repo"
url = "https://github.com/tpope/vim-surround.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/junegunn/start/fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/junegunn/start/fzf.vim"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.vim.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".vim/pack/jiangmiao/start/auto-pairs"]
type = "git-repo"
url = "https://github.com/jiangmiao/auto-pairs.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
type = "git-repo"
url = "https://github.com/wbthomason/packer.nvim.git"
clone.args = ["--depth=1"]
refreshPeriod = "168h"

[".config/plover/main.json"]
type = "file"
url = "https://raw.githubusercontent.com/openstenoproject/plover/main/plover/assets/main.json"
refreshPeriod = "168h"

[".config/plover/commands.json"]
type = "file"
url = "https://raw.githubusercontent.com/openstenoproject/plover/main/plover/assets/commands.json"
refreshPeriod = "168h"

[".config/plover/external/ted-navigation.json"]
type = "file"
url = "http://www.openstenoproject.org/stenodict/dictionaries/cross_platform_movement.json"
refreshPeriod = "168h"

[".config/plover/external/emily-modifiers.json"]
type = "file"
url = "https://raw.githubusercontent.com/EPLHREU/emily-modifiers/master/stuff/emily-modifiers.json"
refreshPeriod = "168h"

[".config/plover/external/emily-symbols.json"]
type = "file"
url = "https://raw.githubusercontent.com/EPLHREU/emily-symbols/master/stuff/emily-symbols.json"
refreshPeriod = "168h"
