import:
  - ~/.config/alacritty/dracula/dracula.yml

scrolling:
  history: 10000

font:
  normal:
    family: Jetbrains Mono
  size: 12.0

key_bindings:
  - { key: F11, action: ToggleFullscreen }

window:
  padding:
    x: 5
    y: 5

background_opacity: 0
