#!/bin/sh

# Monitors
./.screenlayout/main.sh

MONITORS=$(xrandr -q | grep ' connected' | cut -d' ' -f1 | tac)
m_len=$(echo $MONITORS | wc -w)
if test $m_len -gt 1; then
  d_per_m=$((10 / m_len))
  for m in $MONITORS; do
    c=$(echo $m | cut -c1)
    bspc monitor $m -d $({
      n=1
      while test $n -le $d_per_m; do
        echo $c$n
        n=$((n + 1))
      done
    })
  done
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# Bspwm config
bspc config border_width         3
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   '#bbbbbb'
bspc config active_border_color   '#3e953a'
bspc config focused_border_color  '#000000'

# Important keyboard stuff
xmodmap .speedswapper
sxhkd &

# Set up pretty stuff
./.fehbg
xsetroot -cursor_name left_ptr
picom &
redshift -l -38:176 -t 5500:2500 &

# Later pretty stuff

# Delayed to let picom start first
# to avoid flickering
sleep .1s
# -r restart on config change
for m in $MONITORS; do
  MONITOR=$m polybar main -r &
done
