#! /bin/sh

xmodmap .speedswapper
sxhkd &

./.fehbg
xsetroot -cursor_name left_ptr
picom &
redshift -l -38:176 -t 5500:2500 &
polybar main &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   '#122637'
bspc config active_border_color   '#fee409'
bspc config focused_border_color  '#bbbbbb'
