name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux:

    runs-on: ubuntu-latest

    env:
      HOME: ${{ github.workspace }}

    steps:
    - name: Install
      run: curl -L https://git.io/JMTjG | sh
    - name: Check config was successful
      run: |
        test -f $HOME/.zshrc
        test -f $HOME/.config/alacritty/alacritty.yml
        test ! -f $HOME/.skhdrc

  test-macos:

    runs-on: macos-11

    env:
      HOME: ${{ github.workspace }}

    steps:
    - name: Install
      run: curl -L https://git.io/JMTjG | sh
    - name: Check config was successful
      run: |
        test -f $HOME/.zshrc
        test ! -f $HOME/.config/alacritty/alacritty.yml
        test -f $HOME/.skhdrc
